### ISSUE TITLE
Implement VimVentures Wiki

### ISSUE THREAD

**Issue by Ofthemasses** [Ofthemasses/portfolio-website#9]
## Description
The VimVentures wiki is going to be hosted on my portfolio website. This will include generated code docs and a general wiki section.

Related issue: https://github.com/Ofthemasses/VimVentures/issues/2
## To-Do
- [x] Write an introduction section. 
- [x] Write a project philosophy section, this will include more details about the choice of licensing.
- [x] Setup sections for docs and planning.
- ~~Create a GitHub action that updates the code docs automatically.~~ <- This will be updated via the server
- ~~Set up a script to update the wiki with my VimWiki server once a day, so the planning and thought process of this project is open to the public.~~ <- Current provider does not allow for this (syncthing)
